-- Auto-converted from V-Slice stage nonsenseRoomSpace.json
function onCreate()
    makeLuaSprite("spaceBG", "space", -750, -450)
    setScrollFactor("spaceBG", 0.5, 0.5)
    scaleObject("spaceBG", 0.8, 0.8)
    addLuaSprite("spaceBG", false)
    makeLuaSprite("backgroundOtherHalf", "topBGspca", -1150, -900)
    setScrollFactor("backgroundOtherHalf", 1, 1)
    scaleObject("backgroundOtherHalf", 1, 1)
    addLuaSprite("backgroundOtherHalf", false)
    makeLuaSprite("background", "bottombg space", -1150, 280)
    setScrollFactor("background", 1, 1)
    scaleObject("background", 1, 1)
    addLuaSprite("background", false)
    makeLuaSprite("blacksquare", nil, -500, -400)
    makeGraphic("blacksquare", 2600, 1380, "#000000")
    setScrollFactor("blacksquare", 0, 0)
    addLuaSprite("blacksquare", false)
    makeLuaSprite("chair", "chair", 1900, 700)
    setScrollFactor("chair", 1.3, 1.3)
    scaleObject("chair", 1, 1)
    addLuaSprite("chair", false)
    makeLuaSprite("blend", "blend", -400, -400)
    setScrollFactor("blend", 0, 0)
    scaleObject("blend", 1.3, 1.3)
    addLuaSprite("blend", false)
    setProperty('defaultCamZoom', 0.7)
end
