-- Auto-converted from V-Slice stage nonsenseRoomErect.json
function onCreate()
    makeLuaSprite("sky", "sky and city dark", -800, -350)
    setScrollFactor("sky", 0.5, 0.85)
    scaleObject("sky", 0.8, 0.8)
    addLuaSprite("sky", false)
    makeLuaSprite("grass", "outside_dark", 0, 450)
    setScrollFactor("grass", 0.9, 0.9)
    scaleObject("grass", 0.9, 0.9)
    addLuaSprite("grass", false)
    makeLuaSprite("background", "bg", -1150, -700)
    setScrollFactor("background", 1, 1)
    scaleObject("background", 1, 1)
    addLuaSprite("background", false)
    makeLuaSprite("blacksquare", nil, -500, -400)
    makeGraphic("blacksquare", 2600, 1380, "#000000")
    setScrollFactor("blacksquare", 0, 0)
    addLuaSprite("blacksquare", false)
    makeLuaSprite("chair", "chair", 1900, 700)
    setScrollFactor("chair", 1.3, 1.3)
    scaleObject("chair", 1, 1)
    addLuaSprite("chair", false)
    setProperty('defaultCamZoom', 0.7)
end
